domain_searching_task:
  description: >
    Search for domain-specific information related to the medical field, focusing on the latest medical guidelines, treatment protocols, and research papers pertinent to the specified medical scenarios. 
    The search results should be relevant, up-to-date, and provide accurate details that can aid in generating conversations for consultations, treatments, and surgeries between patients and doctors.
    Find the domain specific infomations that takes place during {situation} in the {department} at {date}.
  expected_output: >
    A summary of the search results, including key information, guidelines, or research findings related to the medical scenario.(target language: korean)
  agent: domain_searcher

conversation_generation_task:
  description: >
    Generate a natural conversation between a doctor and a patient based on a medical scenario.
    The conversation should include the patient's symptoms, the doctor's diagnosis, and the prescribed treatment plan.
    The wording of the conversation uses tone like native korean in real situations.
    Create a conversation that takes place during {situation} in the {department} at {date}.
  expected_output: >
    A dialogue script that captures the interaction between the doctor and patient, focusing on symptoms, diagnosis, and treatment recommendations.(target language: korean only)
  agent: conversation_generator
  context:
    - domain_searching_task

intent_extraction_task:
  description: >
    Analyze the generated doctor-patient conversation and extract key medical intents.
    Identify and categorize intentions such as symptom reporting, diagnosis requests, treatment discussions, and follow-up arrangements.
    Intent should be a simple word only.
    Follow the format below:
      * intent1 
          - intent1 keyword (word only)
          - intent1 keyword (word only)
            ...
      * intent2 
          - intent2 keyword (word only)
          - intent2 keyword (word only)
            ...
        ...
  expected_output: >
    A structured list of identified medical intents, each categorized and briefly explained.
    The output should include the context in which each intent was expressed.(target language: korean)
  agent: medical_intent_extractor
  context:
    - conversation_generation_task

consultation_analysis_task:
  description: >
    Analyze the doctor's consultation with the patient and extract key details such as symptoms, diagnosis, and treatment plans.
    The analysis should focus on identifying the most relevant information for creating a medical report.
    The categories would be in SOAP note (an acronym for subjective, objective, assessment, and plan).
  expected_output: >
    A structured set of information extracted from the conversation, including the patient's symptoms, diagnosis, and any prescribed treatments or follow-up recommendations.(target language: korean)
  agent: medical_interpreter
  context:
      - conversation_generation_task
      - intent_extraction_task

report_generation_task:
  description: >
    Based on the analyzed consultation, generate a structured medical report that includes diagnosis, treatment plan, and other relevant patient information in the required format.
    Report must be written in a professional manner and include all necessary sections with a simple word only.
  expected_output: >
    A complete medical report formatted according to the specified guidelines, including sections for patient symptoms, diagnosis, treatments, and follow-up recommendations.(target language: korean)
  agent: medical_report_writer
  context:
    - intent_extraction_task
    - conversation_generation_task
    - consultation_analysis_task
