domain_searching_task:
  agent: domain_searcher
  description: >
    Search for domain-specific information related to the medical field, focusing on the latest therapies, medical treatment protocols, and research papers pertinent to the specified medical scenarios.
    Search results should be relevant, specific, and provide real-world treatment cases that can help generate conversations for consultation, treatment, and surgery between patients and physicians.
    step 1:
    - Define the domain specific situation that takes place during {situation} in the {department} at {date}, patient named {patient_name}.
    step 2:
    - Search for the latest medical kwonledge, treatment protocols, and research papers related to the specified medical scenario.
    
    Let's focus on the treatment procedures and protocols that are most relevant to the patient's symptoms and diagnosis.
    Go! Find the most recent and effective treatment procedures for the patient's condition.
  expected_output: >
    Found threatement procedure note.

conversation_generation_task:
  agent: conversation_generator
  description: >
    Generate a natural conversation between a doctor and a patient based on a medical scenario.
    The conversation should include the patient's symptoms, the doctor's diagnosis, and the prescribed treatment plan.
    The wording of the conversation uses tone like native korean in real situations.
    The Dentist must talk more than the patient just like a real situation.
    Use "~해요" more than "~합니다" in the conversation.
    Create a conversation that takes place during {situation} in the {department} at {date}, patient named {patient_name}.
  expected_output: >
    A dialogue script .txt(target language: korean only)
    <example>
    의사 : ..... (dental domain natural conversation. target language: korean)
    의사 : ..... (dental domain natural conversation. target language: korean)
    환자 : ..... (dental domain natural conversation. target language: korean)
    의사 : ..... (dental domain natural conversation. target language: korean)
    의사 : ..... (dental domain natural conversation. target language: korean)
    의사 : ..... (dental domain natural conversation. target language: korean)
    의사 : ..... (dental domain natural conversation. target language: korean)
    환자 : ..... (dental domain natural conversation. target language: korean)
    ..........(more than 20 turns)
    </example>


intent_extraction_task:
  agent: medical_intent_extractor
  description: >
    Analyze the generated doctor-patient conversation and extract key medical intents.
    Identify and categorize intentions such as symptom reporting, diagnosis requests, treatment discussions, and follow-up arrangements.
    Intent should be a simple word only. DO NOT BREAK DOWN THE INTENTS, JUST LIST UP THE INTENTS.
    Follow the format below:
      * 방문 목적
          - intent keyword
          - intent keyword
            ...
      * 증상 보고
          - intent keyword
          - intent keyword
            ...
      * 진료/상담 내용
          - intent keyword
          - intent keyword
            ...
      * 치료 계획
          - intent keyword
          - intent keyword
            ...
      * 방문 일정 및 비용
          - intent keyword
          - intent keyword
            ...
      ---
      Let's focus on the key intents expressed in the conversation and categorize them accordingly.
  expected_output: >
    A structured list of identified medical intents, each categorized and briefly explained.
    The output should include the context in which each intent was expressed.(target language: korean)

consultation_analysis_task:
  agent: medical_interpreter
  description: >
    Analyze the doctor's consultation with the patient and extract key details such as symptoms, diagnosis, and treatment plans.
    The analysis should focus on identifying the most relevant information for creating a medical report.
    Extract the following information from the conversation:
    <example>
    1. 방문목적: ...
    2. 구강상태: ... 13번과 16번 치아 상태가 안좋음
    3. 구강상태에 대한 치료 방안
        - 상악 전체 틀니
        - 임플란트 지지 틀니
        ...
    4. 상담내용
        - 설명된 치료 상세내용
            - 상악 전체 틀니: 전체 턱에 걸쳐서 장착하는 보철물
            - 임플란트 지지틀니: 임플란트를 식립한 후 임플란트에 틀니를 장착
            ...
        - 진행 예정 치료 및 일정
            - 임플란트 지지 틀니
        - 총 비용
            - 240만원(120만원 씩 두개)
            ...
    </example>
  expected_output: >
    A structured set of information extracted from the conversation, including the patient's symptoms, diagnosis, and any prescribed treatments or follow-up recommendations.(target language: korean)


report_generation_task:
  agent: medical_report_writer
  description: >
    Based on the analyzed consultation, generate a structured medical report that includes diagnosis, treatment plan, and other relevant patient information in the required format.
    Report must be written in a professional manner and include all necessary sections with a simple word only.
    Final report would be formatted with HPI report. If No data in the conversation, you can just pass blank the section.
    - C.C(Chief Complaint)
    - Hx(History of Present Illness)
    - ROS(Review of Systems)
    - PMH(Past Medical History)
    - PSH(Past Surgical History)
    - Medications
    - Allergies
    - FH(Family History)
    - SH(Social History)
    - PE(Physical Examination)
    - Lab Data
    - Assessment
    - Plan
  expected_output: >
    A complete medical report formatted according to the specified guidelines, including sections for patient symptoms, diagnosis, treatments, and follow-up recommendations.(target language: korean)

treatment_searching_task:
  agent: domain_searcher
  description: >
    Search for domain-specific information related to the medical field, focusing on the latest therapies, medical treatment protocols, and research papers pertinent to the specified medical scenarios.
    Search results should be relevant, specific, and provide real-world treatment cases that can help generate conversations for consultation, treatment, and surgery between patients and physicians.
    step 1:
    - Under stand patient's symptom. And do diagnosis with Chain Of Thought method.
    step 2:
    - Search for the medical kwonledge, treatment protocols, and research papers related to the specified medical scenario.
    step 3:
    - Make a treatment plans for the patient.
    - List up all possible treatment plans with bullet points.
    - Give a short details for each treatment plans.
    Let's focus on the treatment procedures and protocols that are most relevant to the patient's symptoms and diagnosis.
    Go! Find the most recent and effective treatment procedures for the patient's condition.
  expected_output: >
    Sujest the treatment procedure note.
